services:
  # Serviço do Backend (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-troque-isso-na-producao
      - ALLOWED_HOSTS=*
      # Configuração do Banco de Dados
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=stock_db
      - DB_USER=stock_user
      - DB_PASSWORD=stock_pass
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=stock_db
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=stock_pass
    ports:
      - "5432:5432"

volumes:
  postgres_data: